#!/usr/bin/env python3
"""Generate the deterministic MuffleSession fault-test harness from the CURRENT product source.

  main.swift          -> systemAudio, address, AudioFailure, check, readNumber, ignoringGone
  MuffleSession.swift -> the whole file
Both are copied verbatim except for one mechanical mapping, so nothing reaches Core Audio,
Dispatch or the system clock at runtime:
  each HAL function                -> Fake<name> in parts/doubles.swift
  DispatchQueue                    -> FakeQueue (held work that the tests run explicitly)
  ProcessInfo.processInfo.systemUptime -> FakeClock.now
  Thread.sleep(forTimeInterval:    -> FakeClock.sleep(forTimeInterval:
  MuffleDSPCreate( / MuffleDSPDestroy( -> FakeDSP.create( / FakeDSP.destroy( (count, then call the real C)
SDK types, constants and CATapDescription stay real; MuffleDSP.c is compiled and linked unchanged.

Usage: ./run.sh   (or: python3 generate.py [--root DIR] [--out FILE])
"""
import argparse
import hashlib
import re
import sys
from pathlib import Path

here = Path(__file__).resolve().parent
parser = argparse.ArgumentParser()
parser.add_argument("--root", type=Path, default=here.parent.parent)
parser.add_argument("--out", type=Path, default=here.parent / ".build" / "muffle.swift")
args = parser.parse_args()

main_path, session_path = args.root / "main.swift", args.root / "MuffleSession.swift"
main = main_path.read_text(encoding="utf-8")
session = session_path.read_text(encoding="utf-8")


def extract(text, marker):
    """Return the declaration starting at `marker` through its matching closing brace."""
    if marker not in text:
        sys.exit(f"main.swift changed shape: missing {marker!r}")
    begin = text.index(marker)
    end = text.index("{", begin) + 1
    depth = 1
    while depth:
        depth += (text[end] == "{") - (text[end] == "}")
        end += 1
    return text[begin:end]


system = re.search(r"^let systemAudio = .*$", main, re.M)
if not system:
    sys.exit("main.swift changed shape: missing `let systemAudio`")
helpers = "\n".join([system.group(0)] + [extract(main, marker) for marker in [
    "func address(", "struct AudioFailure", "func check(", "func readNumber(", "func ignoringGone<"]])

for needle in ["final class MuffleSession", "func start()", "func stop()", "func tick()", "func setPercent(",
               "func setEngaged(", "private final class Route", "func open()", "func close()"]:
    if needle not in session:
        sys.exit(f"MuffleSession.swift changed shape: missing {needle!r}")

hal = ["AudioObjectGetPropertyDataSize", "AudioObjectGetPropertyData", "AudioObjectAddPropertyListenerBlock",
       "AudioObjectRemovePropertyListenerBlock", "AudioHardwareCreateProcessTap", "AudioHardwareDestroyProcessTap",
       "AudioHardwareCreateAggregateDevice", "AudioHardwareDestroyAggregateDevice", "AudioDeviceCreateIOProcID",
       "AudioDeviceDestroyIOProcID", "AudioDeviceStart", "AudioDeviceStop"]
mapping = [(rf"\b{name}\b(?=\s*\()", f"Fake{name}") for name in hal] + [
    (r"\bDispatchQueue\b", "FakeQueue"),
    (r"\bProcessInfo\.processInfo\.systemUptime\b", "FakeClock.now"),
    (r"\bThread\.sleep\(forTimeInterval:", "FakeClock.sleep(forTimeInterval:"),
    (r"\bMuffleDSPCreate\(", "FakeDSP.create("),
    (r"\bMuffleDSPDestroy\(", "FakeDSP.destroy("),
]
counts = {}


def remap(text):
    for pattern, replacement in mapping:
        text, n = re.subn(pattern, replacement, text)
        counts[replacement] = counts.get(replacement, 0) + n
    return text


helpers, session_mapped = remap(helpers), remap(session)
product = helpers + "\n" + session_mapped

# Anything that could still reach the real HAL, Dispatch or the clock fails generation.
types = {"AudioObjectPropertyAddress", "AudioObjectID", "AudioDeviceID"}
leftover = sorted({m.group(1) for m in re.finditer(r"(?<!\w)(Audio(?:Object|Hardware|Device)\w*)\s*\(", product)} - types)
if leftover:
    sys.exit(f"unmapped HAL calls {leftover}: add doubles and mappings for them")
for token in ["DispatchQueue", "DispatchSource", "DispatchSemaphore", "DispatchTime", "ProcessInfo", "Thread.",
              "asyncAfter", "usleep(", "Date()"]:
    if token in product:
        sys.exit(f"mapped source still uses {token!r}")
for required in ["FakeQueue", "FakeClock.now", "FakeDSP.create(", "FakeDSP.destroy(", "FakeAudioDeviceStart"]:
    if not counts.get(required):
        sys.exit(f"MuffleSession.swift changed shape: nothing mapped to {required!r}")

session_sha = hashlib.sha256(session_path.read_bytes()).hexdigest()
main_sha = hashlib.sha256(main_path.read_bytes()).hexdigest()
doubles = (here / "parts" / "doubles.swift").read_text(encoding="utf-8")
tests = (here / "parts" / "tests.swift").read_text(encoding="utf-8")
mapped = ", ".join(f"{name} x{n}" for name, n in counts.items() if n)
header = f"""// GENERATED by tests/muffle/generate.py — do not edit. Product source is copied below,
// verbatim except for the mechanical mapping: {mapped}.
// MuffleSession.swift SHA-256: {session_sha}
// main.swift SHA-256: {main_sha}
let harnessSources = "MuffleSession.swift {session_sha[:12]} · main.swift {main_sha[:12]}"
"""
generated = "\n".join([
    header,
    doubles,
    "// ===== BEGIN main.swift helpers (verbatim, mapped) =====",
    helpers,
    "// ===== END main.swift helpers =====",
    "// ===== BEGIN MuffleSession.swift (verbatim, mapped) =====",
    session_mapped,
    "// ===== END MuffleSession.swift =====",
    tests,
])
args.out.parent.mkdir(parents=True, exist_ok=True)
args.out.write_text(generated, encoding="utf-8")
print(f"wrote {args.out}; {mapped}")
