#!/usr/bin/env python3
"""Generate the Foundation-only harness for the Sigá `App` delegate.

Extracts the CURRENT `struct AudioStatus` and `final class App` from main.swift
by brace matching (no hand-copied production code), then concatenates:
  parts/doubles.swift  (Foundation-only doubles for AppKit/Dispatch/OSLog/ServiceManagement)
  Setup.swift          (verbatim, minus its `import Foundation` line)
  AudioStatus + App    (verbatim from main.swift)
  parts/tests.swift
Never touches the product source; writes only into tests/.build.
"""
import hashlib, json, pathlib, re, sys

HERE = pathlib.Path(__file__).resolve().parent
PROJECT = HERE.parent.parent
OUT = HERE.parent / ".build"
OUT.mkdir(exist_ok=True)
MAIN = PROJECT / "main.swift"
SETUP = PROJECT / "Setup.swift"

def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

def extract(text, header):
    """Return (snippet, first_line, last_line) for the brace-balanced block starting at `header`."""
    start = text.index(header)
    depth, i, in_str = 0, start, False
    while i < len(text):
        c = text[i]
        if in_str:
            if c == "\\": i += 1
            elif c == '"': in_str = False
        elif c == '"': in_str = True
        elif c == "/" and text[i+1] == "/":
            i = text.index("\n", i)
        elif c == "{": depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                end = i + 1
                break
        i += 1
    else:
        raise SystemExit(f"unbalanced block for {header!r}")
    first = text.count("\n", 0, start) + 1
    last = text.count("\n", 0, end) + 1
    return text[start:end], first, last

main = MAIN.read_text(encoding="utf-8")
setup = SETUP.read_text(encoding="utf-8")

app_header = "final class App: NSObject, NSApplicationDelegate, NSMenuDelegate, NSMenuItemValidation {"
status_header = "struct AudioStatus: Equatable {"
assert main.count(app_header) == 1, "App class header not found exactly once"
assert main.count(status_header) == 1, "AudioStatus header not found exactly once"

app_src, app_first, app_last = extract(main, app_header)
status_src, status_first, status_last = extract(main, status_header)
after = main[main.index(app_src) + len(app_src):].lstrip()
assert after.startswith("let app = NSApplication.shared"), "App class is not followed by the script-mode bootstrap; layout changed"

# Substitutions (textual). Keep this list exhaustive; it is copied into the manifest.
substitutions = []
setup_lines = setup.splitlines(keepends=True)
stripped = [l for l in setup_lines if l.strip() != "import Foundation"]
assert len(stripped) == len(setup_lines) - 1, "expected exactly one `import Foundation` in Setup.swift"
substitutions.append({"file": "Setup.swift", "what": "removed the single `import Foundation` line (harness imports Foundation once at the top)"})
setup_body = "".join(stripped)

# Sanity: the App class must not reference anything we do not double.
forbidden = ["import AppKit", "import CoreAudio", "import ServiceManagement", "import OSLog", "AudioObject", "kAudio"]
for word in forbidden:
    assert word not in app_src, f"App class contains {word!r}; harness would not be Foundation-only"

doubles = (HERE / "parts" / "doubles.swift").read_text(encoding="utf-8")
tests = (HERE / "parts" / "tests.swift").read_text(encoding="utf-8")

banner = f"""// GENERATED by generate.py — do not edit. Foundation-only harness for the Sigá `App`.
// main.swift   sha256 {sha(MAIN)}  (App class lines {app_first}-{app_last}, AudioStatus lines {status_first}-{status_last})
// Setup.swift  sha256 {sha(SETUP)}
// Substitutions: {"; ".join(s["what"] for s in substitutions)}
"""
out = "\n".join([
    banner,
    doubles,
    "// ───────── Setup.swift (verbatim, import stripped) ─────────",
    setup_body,
    "// ───────── main.swift: AudioStatus (verbatim) ─────────",
    status_src,
    "// ───────── main.swift: App (verbatim) ─────────",
    app_src,
    "// ───────── tests ─────────",
    tests,
])
(OUT / "app.swift").write_text(out, encoding="utf-8")
manifest = {
    "main.swift": {"sha256": sha(MAIN), "app_lines": [app_first, app_last], "audio_status_lines": [status_first, status_last]},
    "Setup.swift": {"sha256": sha(SETUP)},
    "Welcome.swift": {"sha256": sha(PROJECT / "Welcome.swift"), "note": "not compiled; replaced by a double with the same init/update/setFinishing/showAttention/present surface"},
    "substitutions": substitutions,
    "harness.swift": {"sha256": hashlib.sha256(out.encode()).hexdigest()},
}
(OUT / "app-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
print(f"App class: lines {app_first}-{app_last}; AudioStatus: lines {status_first}-{status_last}; wrote .build/app.swift ({len(out)} bytes)")
