#!/usr/bin/env python3
"""Generate an isolated Foundation-only regression harness for Sigá's `Ducking` class.

The harness is assembled at generation time from the CURRENT product source:
  main.swift  ->  everything from `let systemAudio` through the closing brace of
                  `final class Ducking` is copied verbatim (address/check/readNumber,
                  AudioFailure, SavedVolume, AudioStatus, Ducking).
  parts/doubles.swift -> Core Audio types/constants/C-function doubles, Dispatch doubles
  parts/tests.swift   -> scenarios

No product file is modified. Nothing here imports CoreAudio, AppKit, or Dispatch
symbols: `DispatchQueue`, `DispatchSource`, `DispatchSourceTimer` and every
`AudioObject*` symbol the product code references are module-local doubles that
shadow the SDK names, so the compiled harness performs no Core Audio calls.

Usage:  ../run.sh   (or: python3 generate.py [--main /path/to/main.swift] [--out file.swift])
"""
import argparse
import hashlib
import sys
from pathlib import Path

here = Path(__file__).resolve().parent
default_main = here.parent.parent / "main.swift"

parser = argparse.ArgumentParser()
parser.add_argument("--main", type=Path, default=default_main)
parser.add_argument("--out", type=Path, default=here.parent / ".build" / "ducking.swift")
args = parser.parse_args()

main = args.main.read_text(encoding="utf-8")
sha = hashlib.sha256(main.encode("utf-8")).hexdigest()


def extract(text, marker):
    """Return the declaration starting at `marker` through its matching closing brace."""
    begin = text.index(marker)
    brace = text.index("{", begin)
    depth = 1
    end = brace + 1
    while depth:
        depth += (text[end] == "{") - (text[end] == "}")
        end += 1
    return text[begin:end]


start = main.index("let systemAudio")
ducking = extract(main, "final class Ducking")
end = main.index(ducking) + len(ducking)
core = main[start:end]

# Sanity: the verbatim block must contain what the tests exercise and nothing UI-bound.
for needle in ["func address(", "struct AudioFailure", "func check(", "func readNumber(",
               "struct SavedVolume", "func resolve()", "func write(", "func isRestored(",
               "struct AudioStatus", "final class Ducking", "func terminate(", "func outputChanged()",
               "func manualRestore()", "func fail(", "func restore(", "func verifyRestore(", "func show()"]:
    if needle not in core:
        sys.exit(f"main.swift changed shape: missing {needle!r}")
for forbidden in ["import ", "final class App", "NSApplication", "UserDefaults", "NSMenu"]:
    if forbidden in core:
        sys.exit(f"extracted block unexpectedly contains {forbidden!r}")

first_line = main[:start].count("\n") + 1
last_line = main[:end].count("\n") + 1

doubles = (here / "parts" / "doubles.swift").read_text(encoding="utf-8")
tests = (here / "parts" / "tests.swift").read_text(encoding="utf-8")

header = f"""// GENERATED by generate.py — do not edit. Product source is copied verbatim below.
// Source: {args.main}
// main.swift SHA-256: {sha}
// Verbatim block: main.swift lines {first_line}-{last_line} (systemAudio … end of final class Ducking)
let mainSwiftSHA256 = "{sha}"
let verbatimLines = "{first_line}-{last_line}"
"""

generated = "\n".join([
    header,
    doubles,
    "// ===== BEGIN verbatim product source (main.swift) =====",
    core,
    "// ===== END verbatim product source =====",
    tests,
])
args.out.parent.mkdir(parents=True, exist_ok=True)
args.out.write_text(generated, encoding="utf-8")
print(f"wrote {args.out} ({len(generated)} bytes); main.swift sha256={sha}; verbatim lines {first_line}-{last_line}")
